# Generated by Django 3.0.7 on 2020-07-08 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200707_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='difficulty_level',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quizexercise',
            name='difficulty_level',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=50),
        ),
        migrations.DeleteModel(
            name='DifficultyLevel',
        ),
    ]
