# Generated by Django 3.0.7 on 2020-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200708_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexercise',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='quizexercise',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='projectexercise',
            name='preview',
            field=models.TextField(default='Preview', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizexercise',
            name='preview',
            field=models.TextField(default='Preview', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quizexercise',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
