# Generated by Django 3.0.7 on 2020-07-09 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200708_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitch_profile',
            new_name='medium_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='past_hackathons',
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 7, 9)),
        ),
    ]
