# Generated by Django 3.0.7 on 2020-07-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200709_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
