# Generated by Django 2.2.9 on 2020-07-11 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200709_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 7, 10)),
        ),
    ]
