# Generated by Django 3.0.7 on 2020-07-07 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_extension', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('preview', models.TextField()),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=datetime.date(2020, 7, 7))),
            ],
        ),
    ]
