# Generated by Django 3.0.7 on 2020-07-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='url_extension',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
