# Generated by Django 3.0.7 on 2020-07-09 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200708_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 9)),
        ),
    ]
