# Generated by Django 2.2.9 on 2020-07-11 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200709_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 10)),
        ),
    ]
