# Generated by Django 3.0.4 on 2020-04-07 22:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniexercise',
            name='id',
            field=models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='id',
            field=models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quizexercise',
            name='id',
            field=models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
