# Generated by Django 2.2.9 on 2020-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('searchable_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
            ],
        ),
    ]
