# Generated by Django 3.0.4 on 2020-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200405_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
