# Generated by Django 3.0.4 on 2020-04-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200408_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='submissions_close_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='submissions_open_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='winners_announced',
            field=models.DateTimeField(),
        ),
    ]
