# Generated by Django 3.0.7 on 2020-07-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200702_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('searchable_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PL', 'Programming Language'), ('F', 'Framework'), ('L', 'Library'), ('T', 'Tool')], max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Implementation',
            new_name='MiniImplementation',
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ProjectImplementation'),
        ),
    ]
