# Generated by Django 3.0.7 on 2020-07-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200702_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainteaserexercise',
            name='implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.MiniImplementation'),
        ),
        migrations.AlterField(
            model_name='fixthecodeexercise',
            name='implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.MiniImplementation'),
        ),
        migrations.AlterField(
            model_name='refactorexercise',
            name='implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.MiniImplementation'),
        ),
        migrations.AlterField(
            model_name='teachingexercise',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel'),
        ),
        migrations.AlterField(
            model_name='visualizationexercise',
            name='implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.MiniImplementation'),
        ),
    ]
