# Generated by Django 3.0.7 on 2020-07-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200702_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedprojectexercise',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
