# Generated by Django 3.0.4 on 2020-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200406_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.CharField(default='7sR3pRy7', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='AI04t4NQ', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
