# Generated by Django 3.0.4 on 2020-04-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200406_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.CharField(default='lfg5koPT', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='5i9KpJaL', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='event_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ResourceLink'),
        ),
    ]
