# Generated by Django 3.0.4 on 2020-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200410_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.CharField(default='x3X2dBcV', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
