# Generated by Django 2.2.9 on 2020-07-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200703_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='credits',
            new_name='ranking_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exercise_ranking_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hackathon_ranking_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='overall_ranking_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_ranking_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quiz_ranking_points',
        ),
    ]
