# Generated by Django 3.0.4 on 2020-04-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200407_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='id',
            field=models.CharField(default='AMHI21KY', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='ZQTYr65T', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
