# Generated by Django 3.0.4 on 2020-04-12 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200410_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('searchable_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 12)),
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic'),
        ),
    ]
