# Generated by Django 3.0.4 on 2020-04-13 21:18

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200412_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniexercise',
            name='prerequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='miniexercise',
            name='resources',
            field=models.ManyToManyField(blank=True, to='main.ResourceLink'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 13)),
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='prerequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='resources',
            field=models.ManyToManyField(blank=True, to='main.ResourceLink'),
        ),
        migrations.AlterField(
            model_name='quizexercise',
            name='prerequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='quizexercise',
            name='resources',
            field=models.ManyToManyField(blank=True, to='main.ResourceLink'),
        ),
    ]
