# Generated by Django 3.0.4 on 2020-04-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200413_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniexercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic'),
        ),
        migrations.AlterField(
            model_name='quizexercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic'),
        ),
    ]
