# Generated by Django 3.0.4 on 2020-04-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_difficultylevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniexercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='projectexercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quizexercise',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel'),
        ),
        migrations.AddField(
            model_name='projectexercise',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel'),
        ),
        migrations.AddField(
            model_name='quizexercise',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel'),
        ),
    ]
