# Generated by Django 3.0.4 on 2020-04-14 21:48

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200413_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 14)),
        ),
        migrations.CreateModel(
            name='CompletedQuizExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('quiz_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.QuizExercise')),
            ],
        ),
    ]
