# Generated by Django 3.0.4 on 2020-04-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200414_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_quiz_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedQuizExercise'),
        ),
    ]
