# Generated by Django 3.0.4 on 2020-04-15 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_profile_completed_quiz_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquizexercise',
            name='number_of_correct_answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedquizexercise',
            name='number_of_questions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 15)),
        ),
    ]
