# Generated by Django 3.0.4 on 2020-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200417_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_project_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedProjectExercise'),
        ),
    ]
