# Generated by Django 3.0.4 on 2020-04-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_completed_project_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
