# Generated by Django 3.0.4 on 2020-04-19 01:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quizquestion_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainTeaserExercise',
            fields=[
                ('id', models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('repl_link', models.CharField(max_length=100)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel')),
                ('resources', models.ManyToManyField(blank=True, to='main.ResourceLink')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 18)),
        ),
        migrations.CreateModel(
            name='VisualizationExercise',
            fields=[
                ('id', models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel')),
                ('resources', models.ManyToManyField(blank=True, to='main.ResourceLink')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingExercise',
            fields=[
                ('id', models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel')),
                ('resources', models.ManyToManyField(blank=True, to='main.ResourceLink')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='RefactorExercise',
            fields=[
                ('id', models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('repl_link', models.CharField(max_length=100)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel')),
                ('resources', models.ManyToManyField(blank=True, to='main.ResourceLink')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='FixTheCodeExercise',
            fields=[
                ('id', models.CharField(default=main.models.generate_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('repl_link', models.CharField(max_length=100)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel')),
                ('resources', models.ManyToManyField(blank=True, to='main.ResourceLink')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedVisualizationExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_file', models.FileField(upload_to='')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('visualization_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.VisualizationExercise')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTeachingExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('teaching_exercise_link', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('teaching_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TeachingExercise')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedRefactorExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repl_link', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('refactor_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.RefactorExercise')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedFixTheCodeExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repl_link', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('fix_the_code_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.FixTheCodeExercise')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedBrainTeaserExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repl_link', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('brainteaser_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.BrainTeaserExercise')),
            ],
        ),
    ]
