# Generated by Django 3.0.4 on 2020-04-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0023_quizquestion_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniexercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='miniexercise',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='miniexercise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='miniexercise',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='miniexercise',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='miniexercise',
            name='topic',
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
