# Generated by Django 3.0.4 on 2020-04-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200417_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniexercise',
            name='object_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
