# Generated by Django 3.0.4 on 2020-04-18 03:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200417_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniexercise',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='miniexercise',
            name='object_id',
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='difficulty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel'),
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='prerequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='resources',
            field=models.ManyToManyField(blank=True, to='main.ResourceLink'),
        ),
        migrations.AddField(
            model_name='miniexercise',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Topic'),
        ),
    ]
