# Generated by Django 3.0.4 on 2020-04-18 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200417_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniexercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='miniexercise',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DifficultyLevel'),
        ),
        migrations.AlterField(
            model_name='miniexercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='miniexercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Topic'),
        ),
    ]
