# Generated by Django 3.0.4 on 2020-04-19 16:47

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_completedresearchexercise_researchexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedteachingexercise',
            name='formats',
        ),
        migrations.AddField(
            model_name='teachingexercise',
            name='formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 19)),
        ),
    ]
