# Generated by Django 3.0.4 on 2020-04-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200419_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_brainteaser_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedBrainTeaserExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_fix_the_code_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedFixTheCodeExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_github_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedGitHubExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_refactor_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedRefactorExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_research_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedResearchExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_teaching_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedTeachingExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_visualization_exercises',
            field=models.ManyToManyField(blank=True, to='main.CompletedVisualizationExercise'),
        ),
    ]
