# Generated by Django 3.0.4 on 2020-04-24 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200420_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
        ),
    ]
