# Generated by Django 3.0.7 on 2020-06-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200607_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
    ]
