# Generated by Django 3.0.7 on 2020-06-12 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_profile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_date',
            field=models.DateField(default=datetime.date(2020, 6, 11)),
        ),
    ]
