# Generated by Django 3.0.7 on 2020-06-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('main', '0036_auto_20200611_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.PROTECT, to='djstripe.Customer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.PROTECT, to='djstripe.Subscription'),
        ),
    ]
