# Generated by Django 3.0.7 on 2020-07-06 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_extension', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('preview', models.TextField()),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=datetime.date(2020, 7, 6))),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_extension', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Codeathon', 'Codeathon'), ('Challenge', 'Challenge'), ('Workshop', 'Workshop'), ('Showcase', 'Showcase')], max_length=50)),
                ('preview', models.TextField()),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 7, 6, 9, 39, 41, 528003))),
            ],
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=datetime.date(2020, 7, 6))),
            ],
        ),
    ]
