# Generated by Django 3.0.7 on 2020-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
