# Generated by Django 2.2.9 on 2020-07-04 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date_posted', models.DateField(default=datetime.date(2020, 7, 3))),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 3)),
        ),
    ]
