# Generated by Django 2.2.9 on 2020-07-04 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200703_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 21, 33, 33, 689585))),
            ],
        ),
    ]
