# Generated by Django 2.2.9 on 2020-07-04 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preview',
            field=models.TextField(default='This is a preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='url_extension',
            field=models.CharField(default='test-event', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 21, 39, 21, 62185)),
        ),
    ]
