# Generated by Django 2.2.9 on 2020-07-04 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200703_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('H', 'Hackathon'), ('C', 'Codeathon'), ('CH', 'Challenge'), ('W', 'Workshop'), ('FC', 'Fireside Chat')], default='Challenge', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 22, 18, 35, 454253)),
        ),
    ]
