# Generated by Django 2.2.9 on 2020-07-05 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200703_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='https://w3hacks.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 4)),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 23, 19, 12, 464590)),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 4)),
        ),
    ]
