# Generated by Django 3.0.7 on 2020-07-08 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200707_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 23, 1, 22, 862689)),
        ),
    ]
