# Generated by Django 3.0.7 on 2020-07-08 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200707_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 13, 16, 5, 286451)),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 8)),
        ),
    ]
