# Generated by Django 2.2.9 on 2020-07-11 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200709_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 18, 51, 35, 946534)),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='date_posted',
            field=models.DateField(default=datetime.date(2020, 7, 10)),
        ),
    ]
